### PR TITLE
fixes get_weights. 

### PR DESCRIPTION
**Pull request by alan-stokes**
title:

this includes a basic test

### CODE REVIEW

**Comment by alan-stokes** [comment]
as mentioned, its a basic test that was eye balled that it extracted the weights again. luckily we produce a progress bar for this. Its one of the reasons i added christian to the review, as he is liekly able to put it into the test suites world easier and faster than i.

**Comment by rowleya** [comment]
I think a proper (mostly) unit test can be done to be honest - this would then go in sPyNNaker itself.

**Comment by alan-stokes** [comment]
i concur. just im trying to get the other tasks done, so would like to hand it over. least i can say that the bug has a fix. allows peter to put it in his flow to get his results he needs.

**Comment by rowleya** [comment]
I've added a test to sPyNNaker - this could still be merged if someone is interested

**Comment by alan-stokes** [comment]
when pulled. close issue https://github.com/SpiNNakerManchester/sPyNNaker/issues/258 please

**Pull request merged**
