### PR TITLE
Remove everything and leave a notice

### PR DESCRIPTION
**Pull request by rowleya**

### CODE REVIEW

**Comment by andrewgait** [comment]
I guess we ought to (re-)check before doing this that none of the open PRs in this repository are necessary or relevant any more.  As far as the ones that I had open are concerned, they have or had equivalents in sPyNNaker8, so I don't have a problem with deleting everything.

**Comment by alan-stokes** [comment]
what about the not stale branch called: dvdt_plasticity ?????

**Comment by alan-stokes** [comment]
I think the speed up one was the lingering one from the start of speed up, so deleted it. if it bites me in the butt. meh. given all the support is really in fec

**Comment by rowleya** [comment]
Yes, didn't think to check the branches - I guess we need to see if there is sPyNNaker 8 version of the same thing

**Comment by andrewgait** [comment]
There is but it hasn't been updated recently.  I guess we should ask @chanokin what should be done with this...

**Comment by alan-stokes** [comment]
im persuming stale brnaches....are ....well .....stale and thus not important. but i might be wrong. lol

**Comment by rowleya** [comment]
Of course this branch only actually affects master - other branches will exist (so long as they don't merge in master!)

**Comment by Christian-B** [comment]
Love the idea but would prefer if it is done when master at least passes unit test.

**Comment by andrewgait** [comment]
Another thought on this - there should probably be an equivalent branch / PR for PyNN7Examples.

**Pull request merged**
